# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '12.1'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'BaseFrameWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseFrameWork

  pod 'Alamofire', '~> 5.4'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'BaseFrameWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseFrameWorkUITests' do
    # Pods for testing
  end

end
